apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"basket-prod"},"name":"basket-nodeport","namespace":"basket-prod"},"spec":{"ports":[{"name":"http","port":80,"targetPort":8000}],"selector":{"app":"basket-prod","type":"web"},"type":"NodePort"}}
  creationTimestamp: "2018-03-09T17:11:57Z"
  labels:
    app: basket-prod
  name: basket-nodeport
  namespace: basket-prod
  resourceVersion: "9513418"
  selfLink: /api/v1/namespaces/basket-prod/services/basket-nodeport
  uid: f9069201-23bc-11e8-8eeb-0656fabf84c0
spec:
  clusterIP: 100.68.64.131
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    nodePort: 32162
    port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    app: basket-prod
    type: web
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
