apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "94"
    kubernetes.io/change-cause: jenkins deployed mozmeao/basket:66ada14e56253268ec5198402eddf4752c27fd51
  creationTimestamp: "2018-03-07T20:11:54Z"
  generation: 96
  labels:
    app: basket-stage
    heritage: deis
    type: worker
  name: basket-stage-worker
  namespace: basket-stage
  resourceVersion: "106638441"
  selfLink: /apis/extensions/v1beta1/namespaces/basket-stage/deployments/basket-stage-worker
  uid: c7d81330-2243-11e8-8262-02e6188a289c
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: basket-stage
      heritage: deis
      type: worker
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: basket-stage
        heritage: deis
        type: worker
        version: v100
      name: basket-stage-worker
      namespace: basket-stage
    spec:
      containers:
      - args:
        - bin/run-worker.sh
        command:
        - /bin/bash
        - -c
        env:
        - name: ADMIN_REDIRECT_URL
          valueFrom:
            secretKeyRef:
              key: admin-redirect-url
              name: basket-stage-v100-env
        - name: CELERY_ALWAYS_EAGER
          valueFrom:
            secretKeyRef:
              key: celery-always-eager
              name: basket-stage-v100-env
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              key: database-url
              name: basket-stage-v100-env
        - name: DEBUG
          valueFrom:
            secretKeyRef:
              key: debug
              name: basket-stage-v100-env
        - name: DEIS_APP
          valueFrom:
            secretKeyRef:
              key: deis-app
              name: basket-stage-v100-env
        - name: DEIS_DOMAIN
          valueFrom:
            secretKeyRef:
              key: deis-domain
              name: basket-stage-v100-env
        - name: DISABLE_ADMIN
          valueFrom:
            secretKeyRef:
              key: disable-admin
              name: basket-stage-v100-env
        - name: DONATE_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              key: donate-access-key-id
              name: basket-stage-v100-env
        - name: DONATE_CONTACT_RECORD_TYPE
          valueFrom:
            secretKeyRef:
              key: donate-contact-record-type
              name: basket-stage-v100-env
        - name: DONATE_OPP_RECORD_TYPE
          valueFrom:
            secretKeyRef:
              key: donate-opp-record-type
              name: basket-stage-v100-env
        - name: DONATE_QUEUE_REGION
          valueFrom:
            secretKeyRef:
              key: donate-queue-region
              name: basket-stage-v100-env
        - name: DONATE_QUEUE_URL
          valueFrom:
            secretKeyRef:
              key: donate-queue-url
              name: basket-stage-v100-env
        - name: DONATE_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              key: donate-secret-access-key
              name: basket-stage-v100-env
        - name: EMAIL_HOST
          valueFrom:
            secretKeyRef:
              key: email-host
              name: basket-stage-v100-env
        - name: EMAIL_HOST_PASSWORD
          valueFrom:
            secretKeyRef:
              key: email-host-password
              name: basket-stage-v100-env
        - name: EMAIL_HOST_USER
          valueFrom:
            secretKeyRef:
              key: email-host-user
              name: basket-stage-v100-env
        - name: EMAIL_PORT
          valueFrom:
            secretKeyRef:
              key: email-port
              name: basket-stage-v100-env
        - name: EMAIL_USE_TLS
          valueFrom:
            secretKeyRef:
              key: email-use-tls
              name: basket-stage-v100-env
        - name: ET_CLIENT_ID
          valueFrom:
            secretKeyRef:
              key: et-client-id
              name: basket-stage-v100-env
        - name: ET_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              key: et-client-secret
              name: basket-stage-v100-env
        - name: EXTRA_SUPPORTED_LANGS
          valueFrom:
            secretKeyRef:
              key: extra-supported-langs
              name: basket-stage-v100-env
        - name: FXA_CLIENT_ID
          valueFrom:
            secretKeyRef:
              key: fxa-client-id
              name: basket-stage-v100-env
        - name: FXA_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              key: fxa-client-secret
              name: basket-stage-v100-env
        - name: FXA_EVENTS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              key: fxa-events-access-key-id
              name: basket-stage-v100-env
        - name: FXA_EVENTS_QUEUE_ENABLE
          valueFrom:
            secretKeyRef:
              key: fxa-events-queue-enable
              name: basket-stage-v100-env
        - name: FXA_EVENTS_QUEUE_REGION
          valueFrom:
            secretKeyRef:
              key: fxa-events-queue-region
              name: basket-stage-v100-env
        - name: FXA_EVENTS_QUEUE_URL
          valueFrom:
            secretKeyRef:
              key: fxa-events-queue-url
              name: basket-stage-v100-env
        - name: FXA_EVENTS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              key: fxa-events-secret-access-key
              name: basket-stage-v100-env
        - name: FXA_OAUTH_SERVER_ENV
          valueFrom:
            secretKeyRef:
              key: fxa-oauth-server-env
              name: basket-stage-v100-env
        - name: HTTPS
          valueFrom:
            secretKeyRef:
              key: https
              name: basket-stage-v100-env
        - name: MAINTENANCE_MODE
          valueFrom:
            secretKeyRef:
              key: maintenance-mode
              name: basket-stage-v100-env
        - name: MAINTENANCE_READ_ONLY
          valueFrom:
            secretKeyRef:
              key: maintenance-read-only
              name: basket-stage-v100-env
        - name: NEWRELIC_INI_FILE
          valueFrom:
            secretKeyRef:
              key: newrelic-ini-file
              name: basket-stage-v100-env
        - name: NEW_RELIC_APP_NAME
          valueFrom:
            secretKeyRef:
              key: new-relic-app-name
              name: basket-stage-v100-env
        - name: NEW_RELIC_CONFIG_FILE
          valueFrom:
            secretKeyRef:
              key: new-relic-config-file
              name: basket-stage-v100-env
        - name: NEW_RELIC_LICENSE_KEY
          valueFrom:
            secretKeyRef:
              key: new-relic-license-key
              name: basket-stage-v100-env
        - name: PORT
          valueFrom:
            secretKeyRef:
              key: port
              name: basket-stage-v100-env
        - name: REDIS_CACHE_DB
          valueFrom:
            secretKeyRef:
              key: redis-cache-db
              name: basket-stage-v100-env
        - name: REDIS_CELERY_DB
          valueFrom:
            secretKeyRef:
              key: redis-celery-db
              name: basket-stage-v100-env
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              key: redis-url
              name: basket-stage-v100-env
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              key: secret-key
              name: basket-stage-v100-env
        - name: SENTRY_DSN
          valueFrom:
            secretKeyRef:
              key: sentry-dsn
              name: basket-stage-v100-env
        - name: SFDC_PASSWORD
          valueFrom:
            secretKeyRef:
              key: sfdc-password
              name: basket-stage-v100-env
        - name: SFDC_SEC_TOKEN
          valueFrom:
            secretKeyRef:
              key: sfdc-sec-token
              name: basket-stage-v100-env
        - name: SFDC_USERNAME
          valueFrom:
            secretKeyRef:
              key: sfdc-username
              name: basket-stage-v100-env
        - name: SNITCH_ID
          valueFrom:
            secretKeyRef:
              key: snitch-id
              name: basket-stage-v100-env
        - name: STATSD_CLIENT
          valueFrom:
            secretKeyRef:
              key: statsd-client
              name: basket-stage-v100-env
        - name: STATSD_HOST
          valueFrom:
            secretKeyRef:
              key: statsd-host
              name: basket-stage-v100-env
        - name: STATSD_PREFIX
          valueFrom:
            secretKeyRef:
              key: statsd-prefix
              name: basket-stage-v100-env
        - name: SUPERTOKEN
          valueFrom:
            secretKeyRef:
              key: supertoken
              name: basket-stage-v100-env
        - name: SYNC_KEY
          valueFrom:
            secretKeyRef:
              key: sync-key
              name: basket-stage-v100-env
        - name: TASK_LOCKING_ENABLE
          valueFrom:
            secretKeyRef:
              key: task-locking-enable
              name: basket-stage-v100-env
        - name: WORKFLOW_RELEASE
          valueFrom:
            secretKeyRef:
              key: workflow-release
              name: basket-stage-v100-env
        - name: WORKFLOW_RELEASE_CREATED_AT
          valueFrom:
            secretKeyRef:
              key: workflow-release-created-at
              name: basket-stage-v100-env
        - name: WORKFLOW_RELEASE_SUMMARY
          valueFrom:
            secretKeyRef:
              key: workflow-release-summary
              name: basket-stage-v100-env
        - name: WSGI_NUM_WORKERS
          valueFrom:
            secretKeyRef:
              key: wsgi-num-workers
              name: basket-stage-v100-env
        image: 127.0.0.1:5555/basket-stage:v100
        imagePullPolicy: IfNotPresent
        name: basket-stage-worker
        resources:
          limits:
            memory: 600Mi
          requests:
            memory: 300Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 2
  conditions:
  - lastTransitionTime: "2019-06-25T18:23:41Z"
    lastUpdateTime: "2019-06-25T18:23:41Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2019-02-12T21:55:31Z"
    lastUpdateTime: "2019-07-10T16:42:06Z"
    message: ReplicaSet "basket-stage-worker-5c4c5b9659" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 96
  readyReplicas: 2
  replicas: 2
  updatedReplicas: 2
