apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"basket-stage"},"name":"basket-nodeport","namespace":"basket-stage"},"spec":{"ports":[{"name":"http","port":80,"targetPort":8000}],"selector":{"app":"basket-stage","type":"web"},"type":"NodePort"}}
  creationTimestamp: "2017-07-14T15:16:47Z"
  labels:
    app: basket-stage
  name: basket-nodeport
  namespace: basket-stage
  resourceVersion: "6297579"
  selfLink: /api/v1/namespaces/basket-stage/services/basket-nodeport
  uid: 7454d688-68a7-11e7-8dc9-02859405480d
spec:
  clusterIP: 100.71.112.11
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    nodePort: 32692
    port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    app: basket-stage
    type: web
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
