apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"basket-dev"},"name":"basket-nodeport","namespace":"basket-dev"},"spec":{"ports":[{"name":"http","port":80,"targetPort":8000}],"selector":{"app":"basket-dev","type":"web"},"type":"NodePort"}}
  creationTimestamp: "2018-04-19T08:52:01Z"
  labels:
    app: basket-dev
  name: basket-nodeport
  namespace: basket-dev
  resourceVersion: "18758368"
  selfLink: /api/v1/namespaces/basket-dev/services/basket-nodeport
  uid: ecf3dca1-43ae-11e8-8eeb-0656fabf84c0
spec:
  clusterIP: 100.67.232.231
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    nodePort: 31107
    port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    app: basket-dev
    type: web
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
